version: '3.9'

services:
  frontend:
    build: 
      context: .
      dockerfile: d.frontend.dockerfile
    container_name: frontend
    expose:
      - '80'
    ports:
      - '80:80'
  server:
    build:
      context: .
      dockerfile: d.server.dockerfile
    container_name: server
    expose:
      - '3000'
    ports:
      - '3000:3000'